version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=$SERVER_PORT
    depends_on:
      - db
    networks:
      - mongo
    restart: always

  db:
    image: ${MONGO_VERSION}
    ports:
      - "${MONGO_CONTAINER_PORT}:${MONGO_CONTAINER_PORT}"
    volumes:
      - ./localvolumes/mongo:/data/db
    networks:
      - mongo
    container_name: queue_db
    restart: always

networks:
  mongo:
    driver: bridge